baseurl = "http://ojones.github.io/blog/"
languageCode = "en-us"
title = "Oswald Jones"
theme = "hyde"
copyright = "Oswald Jones"

[Author]
    name = "Oswald Jones"

[Permalinks]
    blog = "/:year/:month/:filename/"
    code = "/:filename/"

[Taxonomies]
    tag = "tags"
    series = "series"
    series-desc = "series-desc"

[params]
    description = "--version dev"
    github = "https://github.com/ojones"

